### ISSUE TITLE
Add a sensitive flag for the deployment variables

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#274]
- [ ] ~~Add a sensitive field to the deployment variables~~.
- [ ] The sensitive field must be encrypted in the database.
- [ ] The sensitive field must be decrypted from the database.
- [ ] ~~The GUI must hide the input~~.
- [ ] ~~The API? (maybe no need to encrypt by the API, HTTPS will do this well?)~~

**Comment by swaroopar** [comment]
@iskey perfect. Had a similar topic in mind. 
Yes, the API is fine as long as SSL is used. 
Regarding DB,  Would it make sense to convert it to one-way hash after deployment is successful? Or if you think the password is not needed in Xpanse after the deployment is successful, we can simply delete it also.

**Comment by swaroopar** [comment]
Hi @iskey ok. If possible we can split the secure fields into two types. One which needs to be stored in xpanse for usecases even after deployment and the ones needed only for deployment.
The ones needed just for deployment may be deleted from the DB after deployment is over.

**Comment by iskey** [comment]
`SensitiveTemporaryStored ` may be not clear enough, actually, this kind of variable will not be stored anywhere but in the memory.
 How about like this:
```java
enum SensitiveScope {
    None("none"),
    Once("once"),
    Always("Always");

    private final String scope;

    SensitiveScope(String currency) {
        this.scope = currency;
    }
}
```

**Comment by swaroopar** [comment]
@iskey this is even better. 
Just regarding comments, "Always" - Data required in all life cycles of the service. This data will be encoded/encrypted and stored so that it can be decoded/decrypted whenever required. Will be deleted when the service is deleted/destroyed.
"Once" - Data is required in the only request in which it is passed. This data will be encoded/encrypted and stored and will be deleted when the request is successfully processed. 

Does this also match your understanding?

**Comment by iskey** [comment]
The unfinished issues will be completed by #557, #558
