### ISSUE TITLE
Design the GUI of the Monitor

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#293]
- [ ] Design for the GUI part of the monitor.

**Comment by Alice1319** [comment]
@iskey @swaroopar @WangLiNaruto 
This is the design page for Monitor, please take a look.

![image](https://user-images.githubusercontent.com/42802200/233817199-958a1a2f-58a5-484d-a86a-d9d45d0e9a68.png)
![image](https://user-images.githubusercontent.com/42802200/233817209-939c98ff-1275-43bd-b08c-ba5ccc9c2cde.png)

**Comment by swaroopar** [comment]
@Alice1319 this looks good. Can you also please add the 'customerServiceName' drop down? 

https://github.com/eclipse-xpanse/xpanse/blob/main/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/CreateRequest.java#L51

Also for the service name drop down, I see some hash value appended to it. If it just in the design and will not be part of the real implementation then good. Otherwise, we can consider removing it.

**Comment by Alice1319** [comment]
@iskey @swaroopar @WangLiNaruto
The design has been updated, please take a look.
![image](https://user-images.githubusercontent.com/42802200/233960195-8b30e43b-2a36-419d-b121-c21ff0a11700.png)

**Comment by swaroopar** [comment]
@Alice1319 looks good for me.

**Comment by iskey** [comment]
looks good.
